apiVersion: v1
kind: Pod
metadata:
  labels:
    agent: siteweb
spec:
  imagePullSecrets:
    - name: svc-images-reader-it-group
  tolerations:
    - key: env
      value: prd
      effect: NoSchedule
  nodeSelector:
    env: prd
  containers:
    - name: jnlp
      env:
        - name: CONTAINER_ENV_VAR
          value: jnlp
    - name: curl
      image: alpine/curl:3.14
      command:
        - sleep
      args:
        - infinity
    - name: zip
      image: nsnow/zip
      command:
        - sleep
      args:
        - infinity